srun --pty --partition=cbcb-heng --account=cbcb-heng --qos=medium \
    --mem-per-cpu=64G --gres=gpu  --time=1:00:00 \
    ../../miniconda3/clap/bin/python -m laion_clap.training.main \
        --save-most-recent \
        --datasetpath="data/audiocaps/audio_files/train" \
        --precision="fp32" \
        --batch-size=96 \
        --lr=1e-2 \
        --wd=0.0 \
        --epochs=20 \
        --use-bn-sync \
        --tmodel roberta \
        --amodel HTSAT-tiny \
        --resume models/630k-audioset-best.pt \
        --datasetnames "audiocaps" \
        --top-k-checkpoint-select-dataset="AudioCaps-test" \
        --top-k-checkpoint-select-metric="mAP@10" \
        --logs 'logs' \
        --seed 3407 \
        --gather-with-grad \
        --optimizer "adam" \
        --data-filling "repeatpad" \
        --data-truncating "rand_trunc" \
        --prefetch-factor 2 \
        --report-to "wandb" \
        --wandb-notes "finetune-audiocaps"
